#!/bin/bash
code --install-extension aaron-bond.better-comments
code --install-extension adpyke.codesnap
code --install-extension haskell.haskell
code --install-extension hoovercj.haskell-linter
code --install-extension James-Yu.latex-workshop
code --install-extension justusadam.language-haskell
code --install-extension KevinRose.vsc-python-indent
code --install-extension ms-python.black-formatter
code --install-extension ms-python.isort
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-toolsai.vscode-jupyter-cell-tags
code --install-extension ms-toolsai.vscode-jupyter-slideshow
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode.cmake-tools
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.cpptools-extension-pack
code --install-extension ms-vscode.cpptools-themes
code --install-extension ms-vscode.remote-explorer
code --install-extension naumovs.color-highlight
code --install-extension njpwerner.autodocstring
code --install-extension PKief.material-icon-theme
code --install-extension redhat.vscode-yaml
code --install-extension rust-lang.rust-analyzer
code --install-extension SonarSource.sonarlint-vscode
code --install-extension stkb.rewrap
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension tamasfe.even-better-toml
code --install-extension tecosaur.latex-utilities
code --install-extension timonwong.shellcheck
code --install-extension tomoki1207.pdf
code --install-extension trond-snekvik.simple-rst
code --install-extension twxs.cmake
code --install-extension valentjn.vscode-ltex
code --install-extension VisualStudioExptTeam.intellicode-api-usage-examples
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension zhuangtongfa.material-theme
